version: '2'
services:
  nginx:
    container_name: nginx_${CURRENT_NAME}
    restart: always
    build: nginx/
    ports:
      - "${CURRENT_PORT}:${CURRENT_PORT}"
      #- "8081:8081"
    volumes:
      - /www/static
    volumes_from:
      - server
      #- client
    links:
      - server:server
      #- client:client  
  
  postgres:
    image: postgres_${CURRENT_NAME}
    environment:
      - POSTGRES_USER=erp
      - POSTGRES_PASSWORD=erp123
      - POSTGRES_DB=db_erp
    #ports:
    #  - '5432:5432'

  server:
    container_name: server_${CURRENT_NAME}
    restart: always
    build: .
    working_dir: /usr/src/app
    command: /usr/local/bin/gunicorn erp_cms.wsgi:application -w 2 -b :8000 --reload
    environment:
      - DATABASE_URL=postgres://erp:erp123@postgres/db_erp
      - DEFAULT_FROM_EMAIL=testnubiquo@gmail.com
    volumes:
      - ./server:/usr/src/app
      - ./static:/usr/src/static
      - ./templates:/usr/src/templates
      - ./theme_configs.py:/usr/src/app/erp_cms/theme_configs.py
    #ports:
    # - '8000:8000'
    expose:
      - "8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres

  # client:
  #   container_name: client
  #   #restart: always
  #   build: dashboard_web_client/
  #   working_dir: /www/app
  #   #command: sh run.sh
  #   volumes:
  #     - ./dashboard_web_client:/www/app
  #   #ports:
  #   #  - '4200:4200'
  #   expose:
  #     - "4200"
