# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interest_group', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('hash_invitation', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'A la espera'), (1, 'Aceptada'), (2, 'Expirada')], default=0)),
            ],
            options={
                'abstract': False,
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='interestgroup',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime(2016, 5, 12, 19, 27, 2, 418745, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='header_image',
            field=models.ImageField(default='group/header/default.png', upload_to='group/header/'),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='short_description',
            field=models.TextField(default='descripcion corta', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 12, 19, 27, 23, 741835, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='image',
            field=models.ImageField(default='group/default.png', upload_to='group'),
        ),
        migrations.AddField(
            model_name='suscription',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscriptions', to='interest_group.InterestGroup'),
        ),
    ]
