# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interest_group', '0003_auto_20160512_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suscription',
            name='email',
            field=models.EmailField(blank=True, null=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='suscription',
            name='hash_invitation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='suscription',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Preaproved'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Expired')], default=0),
        ),
    ]
