# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_group', '0006_auto_20160529_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestgroup',
            old_name='header_image',
            new_name='image_header',
        ),
    ]
