# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_group', '0007_auto_20160530_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgroup',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='slug',
            field=models.SlugField(auto_created=True, editable=False, unique=True),
        ),
    ]
